apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: test-sjm-tpa-python3
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/sjmrhtap/test-sjm-tpa-python3:3ab8ae007b82ab84eb03878355a657d96b9e4d54@sha256:f02c651c1c0c6da9da55efbc831d655617ba90b0949f2547ae94fcde184cd127
        name: container-image  
